pipeline:

  build:
    image: docker:18.03-dind
    commands:
      - docker build -t telebot:${DRONE_COMMIT} .
    volumes

  deploy:
    image: docker:18.03-dind
    environment:
      - TELEBOT=${TELEBOT_TOKEN}
    commands:
      - docker run -d --name telebot telebot:${DRONE_COMMIT}
