pipeline:

  build:
    image: docker:18.03
    commands:
      - docker build -t telebot:${DRONE_COMMIT} .
    environment:
      - TELEBOT=${TELEBOT_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  deploy:
    image: docker:18.03
    commands:
      - docker run -d --name telebot/$$BUILD_NUMBER telebot:${DRONE_COMMIT}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
